import imgHTML from './../assets/html.png';
import imgCSS from './../assets/css.png';
import imgJS from './../assets/js.png';
import imgReact from './../assets/react.png';
import imgNative from './../assets/reactnative.png'
import imgTailwind from './../assets/tailwindcss.png';
import imgBootstrap from './../assets/Bootstrap.png';
import imgNode from './../assets/node.png';
import imgPhp from './../assets/php.png';
import imgMySql from './../assets/mysql.png';
import imgMongoDb from './../assets/mongodb.png';
import imgMariaDb from './../assets/mariadb.png';


export const schoolData = [
    {id: 1, von: "", bis: "", titel: "div. autodidakte Weiterbildungen", kurz: "Rheinwerk-Verlag, Udemy, etc.", tasks: "Mit YouTube, Udemy und dem Rheinwerk-Verlag bilde ich mich regelmäßig weiter oder versuche meine Kentnisse zu vertiefen."},
    {id: 2, von: "", bis: "seit 2020", titel: "Handlungsvollmacht", kurz: "Bereichsleiter mit Handlungsvollmacht", tasks: "2020 wurde mir die Handlungsvollmacht übertragen. In diesem Zuge bekam ich einen neuen Vertrag als Bereichsleiter.<br/>Als Bereichsleiter war ich für die Bereiche 'Operating', 'Datencenter', 'Entwicklung' und 'Interventionsstelle' zuständig."},
    {id: 3, von: "", bis: "seit 2021", titel: "Ausbilder", kurz: "Fachkraft für Schutz und Sicherheit", tasks: "Als Ausbilder ist meine Hauptaufgabe, die Inhalte der Ausbildungsverordnung gründlich zu vermitteln, um sicherzustellen, dass meine Auszubildenden ein fundiertes Verständnis für ihr Fachgebiet entwickeln. Darüber hinaus unterstütze ich sie aktiv dabei, praktische Fähigkeiten zu erlernen und fördere ihre persönliche und berufliche Entwicklung. In meiner Rolle als Ausbilder habe ich bereits erfolgreich fünf Auszubildende durch ihre Ausbildung begleitet und sie auf dem Weg zu einem erfolgreichen Abschluss unterstützt.",
    attachment:"ada.pdf", attDesc:"Ausbilderbescheinigung + IHK-Zulassung"},
    {id: 4, von: "", bis: "seit 2020", titel: "L-NSL-FK", kurz: "Leitende NSL-Fachkraft", tasks: "Als leitende NSL-Fachkraft bin ich für die Leitung und Organisation der Notruf- und Serviceleitstelle verantwortlich. Das bedeutet, ich koordiniere alle Abläufe und Prozesse innerhalb der Leitstelle, um sicherzustellen, dass alle eingehenden Notrufe und Serviceanfragen effizient bearbeitet werden. Ich überwache das Personal, plane Schichten und sorge dafür, dass alle Mitarbeiterinnen und Mitarbeiter geschult sind, um in Notfallsituationen angemessen zu reagieren. Kurz gesagt, meine Aufgabe ist es, dafür zu sorgen, dass die Leitstelle reibungslos funktioniert und Menschen in Not schnell und effektiv Hilfe erhalten.",
    attachment:"LNSLFk.pdf", attDesc:"Zertifikat"},
    {id: 5, von: "", bis: "seit 2018", titel: "Sicherheitsbeauftragter", kurz: "", tasks: "Als Sicherheitsbeauftragter betrugen meine Aufgaben die Überwachung und Sicherstellung der Arbeitsplatzsicherheit innerhalb des Unternehmens. Dazu gehörte die regelmäßige Identifizierung potenzieller Gefahren und Risiken, um geeignete Maßnahmen zur Risikominimierung zu entwickeln und umzusetzen. Des Weiteren war es meine Verantwortung, Schulungen und Unterweisungen für die Mitarbeiter durchzuführen, um das Bewusstsein für Sicherheitsfragen zu stärken und sicherheitsrelevante Verhaltensweisen zu fördern. Zusätzlich habe ich die Einhaltung der Sicherheitsstandards und -vorschriften überwacht und Unfälle oder Sicherheitsvorfälle untersucht, um Verbesserungsmöglichkeiten aufzuzeigen und die Sicherheitspraktiken kontinuierlich zu optimieren.",
    attachment:"Sicherheitsbeauftragter.pdf", attDesc:"Einbestellung"},
    {id: 6, von: "", bis: "seit 2017", titel: "Betriebsleiter", kurz: "Betriebsleiter der Alarmempfangsstelle GmbH", tasks: "2017 wurde ich vom Schichtleiter zum Betriebsleiter befördert und bekam einen Vertrag als leitender Angestellter."},
    {id: 7, von: "2003", bis: "2006", titel: "Fachkraft für Schutz und Sicherheit", kurz: "Berufschule Neuburg a.d. Donau", tasks: "Die Ausbildungsinhalte für die kaufmännische Ausbildung zur Fachkraft für Schutz und Sicherheit umfassten unter anderem folgende Punkte:<br/><br/>Rechtliche Grundlagen <br/>Einführung in relevante Gesetze und Vorschriften, wie das Sicherheitsgewerbe-Gesetz und Datenschutzbestimmungen.<br/><br/>Sicherheitstechnik: <br/>Bedienung und Wartung von Sicherheitssystemen wie Alarmanlagen, Überwachungskameras und Zutrittskontrollsystemen.<br/><br/>Gefahrenabwehr und Notfallmanagement: <br/>Analyse von Gefahrensituationen und angemessene Reaktionen auf Notfälle wie Brände, Diebstähle oder andere Bedrohungen.<br/><br/>Kommunikation und Konfliktmanagement:<br/>Entwicklung von kommunikativen Fähigkeiten und Strategien zur Deeskalation von Konflikten in sicherheitsrelevanten Situationen.<br/><br/>Sicherheitsrecht und Sicherheitsmanagement: <br/>Erstellung von Sicherheitskonzepten, Koordination von Sicherheitsmaßnahmen und Zusammenarbeit mit Behörden und anderen Sicherheitsdiensten.<br/><br/>Erste Hilfe: <br/>Grundlegende Kenntnisse und Fertigkeiten in Erster Hilfe, um im Notfall schnell und angemessen handeln zu können.<br/><br/>Die kaufmännische Ausbildung ermöglicht ein breites Verständnis betriebswirtschaftlicher Aspekte, Büroorganisation, Kundenkommunikation, rechtlicher Rahmenbedingungen, Marketing, Vertrieb und Projektmanagement und ist in verschiedenen Geschäftsbereichen anwendbar.",
    attachment:"fkss.pdf", attDesc:"FkSS-Zeugnis"}
];

export const professionData = [
    {id: 1, von: "12/2014", bis: "heute", titel: "Bereichsleitung", kurz: "BAVADO Holding GmbH", tasks: "Zusammengefasst umfasste meine Tätigkeit folgende Aufgaben:<br/><br/>Verwaltung: <br/>Planung und Steuerung der Abläufe, Reklamationsmanagement, Vorbereitung für Zertifizierungen (u.a. ISO, VdS)<br/><br/>Personal: <br/>Ein- & Ausstellungen, Personalplanung, Führen von Mitarbeitergesprächen, Dienst- und Urlaubsplanung, Vorbereitung der Lohnbuchhaltung<br/><br/>Technik: <br/>Aufbau und Wartung der Arbeitsplätze, Einrichtung und Verwaltung der Diensthandys und Laptops, technischer Support für Mitarbeiter (24/7), Rückfallebene für die gesamte technische Infrastruktur der Notrufleitstelle<br/><br/>Entwicklung:<br/>Allgemeine Programmierung und Weiterentwicklung der Leitstellensoftware", attachment:"bavadozeugnisse.pdf", attDesc:"Bestätigungen"},
    {id: 2, von: "11/2012", bis: "11/2014", titel: "Nightmanager Holiday Inn, Ibis Messe, Novotel Messe", kurz: "Securitas GmbH & Co.KG", tasks: "Zurück zu Securitas war ich in den Hotels Novotel Messe, IBIS Messe und Holiday Inn Munich City Centre als Night Audit eingeteilt.<br/>Nach kurzer Zeit wurde ich von den Kunden direkt als Night Manager gebucht. Meine Aufgaben waren unter anderem Check-In, Check-Out der Gäste, allgemeinen Kundenkontakt, Rundgänge, Tagesabrechnungen sowie Frühstücksvorbereitung und ab und zu Room-Service.", attachment:"", attDesc:""},
    {id: 3, von: "06/2011", bis: "10/2012", titel: "Leitung Innendienst", kurz: "AQUACOMET GmbH", tasks: "Für die Firma Aquacomet GmbH baute ich die eigens in Ungarn hergestellten Schwimmbadüberdachungen auf.<br/><br/>Ab Juni 2011 wechselte ich dann in den Innendienst und übernahm dort die Leitung.", attachment:"", attDesc:""},
    {id: 4, von: "07/2010", bis: "05/2011", titel: "Montageleitung Schwimmbadüberdachungen", kurz: "AQUACOMET GmbH", tasks: "Für die Firma Aquacomet GmbH baute ich die eigens in Ungarn hergestellten Schwimmbadüberdachungen auf.<br/><br/>Ab Juni 2011 wechselte ich dann in den Innendienst und übernahm dort die Leitung.", attachment:"", attDesc:""},
    {id: 5, von: "03/2007", bis: "06/2010", titel: "Schichtleiter BMW Welt", kurz: "Securitas GmbH & Co.KG", tasks: "Als Schichtleiter wurde ich von SECURITAS GmbH und Co. KG in der BMW Welt eingesetzt.<br>Meine Aufgaben während des bau´s lagen unter anderem in der Zugangskontrolle, Objektrundgänge und der allgemeine Sicherheit.Nach Eröffnung war ich als Schichtleiter im Group Security Center der BMW Welt eingesetzt.", attachment:"", attDesc:""},
    {id: 6, von: "08/2006", bis: "02/2007", titel: "FKSS in diversen Objekten", kurz: "WWD GmbH", tasks: "Nach meiner Ausbildung war ich für die Firma WWD GmbH in München tätig und wurde als Fachkraft bei diversen Kunden im Objektschutz eingesetzt.", attachment:"", attDesc:""},
    {id: 7, von: "09/2003", bis: "07/2006", titel: "Ausbildung Fachkraft für Schutz und Sicherheit", kurz: "GfSmbH (heutige BAVADO Holding GmbH)", tasks: "Die Ausbildungsinhalte für die kaufmännische Ausbildung zur Fachkraft für Schutz und Sicherheit umfassten unter anderem folgende Punkte:<br/><br/>Rechtliche Grundlagen <br/>Einführung in relevante Gesetze und Vorschriften, wie das Sicherheitsgewerbe-Gesetz und Datenschutzbestimmungen.<br/><br/>Sicherheitstechnik: <br/>Bedienung und Wartung von Sicherheitssystemen wie Alarmanlagen, Überwachungskameras und Zutrittskontrollsystemen.<br/><br/>Gefahrenabwehr und Notfallmanagement: <br/>Analyse von Gefahrensituationen und angemessene Reaktionen auf Notfälle wie Brände, Diebstähle oder andere Bedrohungen.<br/><br/>Kommunikation und Konfliktmanagement:<br/>Entwicklung von kommunikativen Fähigkeiten und Strategien zur Deeskalation von Konflikten in sicherheitsrelevanten Situationen.<br/><br/>Sicherheitsrecht und Sicherheitsmanagement: <br/>Erstellung von Sicherheitskonzepten, Koordination von Sicherheitsmaßnahmen und Zusammenarbeit mit Behörden und anderen Sicherheitsdiensten.<br/><br/>Erste Hilfe: <br/>Grundlegende Kenntnisse und Fertigkeiten in Erster Hilfe, um im Notfall schnell und angemessen handeln zu können.<br/><br/>Die kaufmännische Ausbildung ermöglicht ein breites Verständnis betriebswirtschaftlicher Aspekte, Büroorganisation, Kundenkommunikation, rechtlicher Rahmenbedingungen, Marketing, Vertrieb und Projektmanagement und ist in verschiedenen Geschäftsbereichen anwendbar.", attachment:"fkss.pdf", attDesc:"FkSS-Zeugnis"},
    {id: 8, von: "06/2002", bis: "08/2003", titel: "Praktikum Notrufzentrale", kurz: "GfSmbH (heutige BAVADO Holding GmbH)", 
    tasks: `Direkt nach der Schule absolvierte ich ein einjähriges Praktikum in der Notrufzentrale der Firma GfSmbH am Tegernseer Platz 4 in München.\n\nHier durfte ich die verschiedenen Bereiche eines Sicherheitsdienstleistungsunternehmens kennenlernen.
\nDer Einblick, den ich durch das Praktikum bekommen habe, sorgte dafür, dass ich mich für das nachfolgende Ausbildungsjahr für die Ausbildung zur Fachkraft für Schutz und Sicherheit bewarb.\n`,
    attachment:"", attDesc:""},
];

export const skillImages = 
{
    frontend: [imgHTML, imgCSS, imgJS, imgReact, imgNative, imgBootstrap, imgTailwind],
    backend: [imgNode, imgPhp],
    database: [imgMySql, imgMongoDb, imgMariaDb]
};

export const portfolioList = [
    {id:1, titel: "BAVADO plus", desc: "Intranet", core: "Electron/React", img: 23, imgPath: "bavadoplus", longDesc:"Programmiert mit Electron, React, Node und PHP<br/><br/>React-Router, Redux, axios, Bootstrap<br/><br/>Ein gesellschaftsübergreifendes Intranet für die Führungskräfte der Gesellschaften in der BAVADO Holding Gruppe.<br/><br/>Electron wurde als Art Container benutzt, um die React-Anwendung nicht im Browser starten zu müssen, sondern als .exe-Anwendung.<br/><br/>Kurzübersicht der Funktionen:<br/><br/>Berechtigungsgesteuert mit einem binären Rechtesystem (Zweierpotenz)<br/><br/>News, Pinnwand mit Neuigkeiten<br/><br/>Dokumentenmanagementsystem<br/><br/>Organigramm, Telefonverzeichnis, Userverwaltung<br/><br/>Firmenrichtlinienanzeige anzeigen/erstellen/bestätigen<br/><br/>Ideenschmiede<br/><br/>Budgetvereinbarungen, Kostenstellen, Ergebniszahlen, Gutschriften<br/><br/>Materialanforderungen, Auslagenabrechnungen, Einkauf,<br/><br/>Monatsberichte, Fuhrparkmanagement, Protokollwesen", attachment:"", attDesc:""},
    {id:2, titel: "Bavaleo App", desc: "Mitarbeiter-App", core: "React Native", img: 18, imgPath: "bavaleoapp", longDesc:"Programmiert mit React Native und PHP<br/><br/>Gesellschaftsübergreifende Mitarbeiter-App für Android & iOS<br/><br/>Funktionen:<br/><br/>News – Neuigkeiten der BAVADO Holding Gruppe (Berechtigungsgesteuert).<br/><br/>„Gefällt mir“-Funktion, Bestätigungsfunktion, Kommentarfunktion<br/><br/>Kalender – Anzeige von Schulungen, Lehrgängen, Meetings, etc.<br/><br/>Telefonverzeichnis – Berechtigungsgesteuerte Anzeige der Führungskräfte<br/><br/>Daten (Name, Position, Telefonnummer, E-Mail-Adresse, etc.) aller Abteilungen und Gesellschaften<br/><br/>Dienstplan, DATEV-Weiterleitung, Mitarbeiterangebote<br/><br/>Ideenschmiede – Möglichkeit für Mitarbeiter, Verbesserungsvorschläge einzureichen", attachment:"bavaleoAnleitung.pdf", attDesc:"App-Anleitung"},
    {id:3, titel: "Aufzugswärter App", desc: "Revierinterne App", core: "JQuery", img: 7, imgPath: "awapp", longDesc:"Programmiert mit JQuery und PHP<br/><br/>2017 nahmen wir als Dienstleistung die Aufzugswärter-Kontrollen mit auf.<br/>Hier galt es nach einer Kundenspezifischen Checkliste Aufzüge und deren Gegebenheiten zu kontrollieren und zu protokollieren.<br/><br/>Um das ganze zu vereinfachen und zu digitalisieren, habe ich mit der Aufzugswärter-App meine erste App für die BAVADO Holding geschrieben.<br/><br/>Der Mitarbeiter loggt sich mit seiner Personalnummer ein und sieht auf der Startseite sämtliche Aufzüge, die in seinem zugeordneten Bereich noch zu kontrollieren sind.<br/><br/>Mit einem Klick auf einen Aufzug, wird eine Detailansicht der Anlage angezeigt und die Überprüfung kann gestartet werden.<br/><br/>Je nach Kundenwunsch stehen verschiedene Punkte zum Überprüfen an, wie z.B. 'Steht der Aufzug in jeder Etage bündig?' etc.<br/><br/>Das Ergebnis wird im Backend ausgewertet und es wird eine PDF erstellt, die dem jeweiligen Kunden per E-Mail zugesendet wird.<br/><br/>Als Server dient ein Rapsberry Pi, der täglich einen Cron-Job ausführt um die Zuordnungen und Intervalle zu prüfen.<br/>Zudem schickt er wöchentlich eine E-Mail an alle Zuständigen Bereiche mit der Anzahl der noch zu überprüfenden Anlagen und macht jeden ersten des Monats eine Statistik, ob alle Anlagen überprüft wurden und setzt die neu zu prüfenden Anlagen wieder in die App.", attachment:"BeispielAWPDF.pdf", attDesc:"Beispiel-PDF"},
    {id:4, titel: "SchieferWohnen", desc: "AlarmanlagenApp", core: "React Native", img: 3, imgPath: "schieferwohnen", longDesc:"Programmiert mit React Native, Python und PHP - GSM Übertragungsprotokoll: TCP/IP<br/><br/>Die mobile Alarmanlage wurde aus einem Raspberry Pi, einem Bewegungssensor, ein kleiner LED-Ring, einer Kamera, einem Gassensor, ein SIM-Modul und einem Luftfeuchtigkeitssensor für ein Wohnmobil aufgebaut.<br/>Als Stromquelle dient die Autobatterie des Wohnmobils.<br/><br/>Mit der App lässt sich die Alarmanlage scharf/unscharf schalten, Informationen auslesen und die ausgelösten Alarmbilder ansehen.", attachment:"", attDesc:""},
    {id:5, titel: "Dienstplan", desc: "zur Vorplanung", core: "VBA", img: 0, imgPath: "dienstplan", longDesc:"Für eine einfache und schnelle Vorbereitung der Dienstplanung, habe ich in Excel/VBA ein kleines Dienstplanungsprogramm geschrieben.<br/><br/>Wochenende und Feiertag wird je nach angegebenen Monat und Jahr automatisch eingefärbt.<br/>Die zu verplanenden Schichten werden je nach Wochentag angezeigt.<br/><br/>Anzeige für fehlende Schichten, doppelt vergebene Schichten oder Unterschreitung der einzuhaltenden Pausenzeiten.", attachment:"", attDesc:""},
    {id:6, titel: "IV-Auswertung", desc: "Interventionsstatistik", core: "VBA, PHP", img: 0, imgPath: "iva", longDesc:"Programmiert mit Excel/VBA und PHP<br/><br/>Alle gefahrenen Interventionen, Sonderkontrollen, Standwachen, etc. werden in der Leitstellensoftware in einer MySQL-Datenbank gespeichert.<br/>Die Einsatz-Datenbank zusammen mit den Kundendatenbanken werden am Monatsanfang exportiert und über das Excel-Programm eingelesen.<br/><br/>Über VBA werden die Daten ausgewertet und eine TXT-Datei erstellt, die dann per E-Mail an ein Postfach gesendet wird.<br/><br/>Ein PHP-Script öffnet die E-Mail, liest die Daten aus, erstellt dann für jede Niederlassung eine PDF-Datei und speichert sie auf dem Server.<br/>Anschließend wird die E-Mail gelöscht.<br/><br/>Die Auswertungen werden den zuständigen Mitarbeitern über das Intranet zur Verfügung gestellt.<br/><br/>Als 'Nebenprodukt' erstellt das Excel-Programm noch zwei weitere Dateien für die Faktura. Eine Provisionsliste der Subunternehmer und eine Provisionsliste für Errichter.", attachment:"Auswertung_Beispiel.pdf", attDesc:"Beispiel-Auswertung"},
    {id:7, titel: "Fels", desc: "Leitstellensoftware", core: "Vanilla JS", img: 0, imgPath: "fels", longDesc:"Maßnahmenseiten, Statistiken, Tools - unsere Leitstellensoftware basiert auf Vanilla JS.<br/><br/>Meine Aufgabe war die Weiterentwicklung, Neuprogrammierung und Änderung von bestehenden Scripts.<br/>Zudem habe ich ältere Bestandteile Stück für Stück von VBS auf JavaScript umgeschrieben.", attachment:"", attDesc:""},
    {id:8, titel: "Portfolio Homepage", desc: "Diese Seite", core: "React", img: 0, imgPath: "pf", longDesc:"GitHub-Link: https://github.com/AOS1986/PF.git", attachment:"", attDesc:""},
];


//projekte:
/*





Bavado plus
Bavaleo App + anleitung
Aufzugswärter App
schiefer wohnen
bilder png in jpg umwandeln
Exceldienstplan!!!
Interventionsstatistik

div. Erweiterungen der Leitstellensoftware in Vanilla JS - umprogrammierung von alten VBS Scripten auf JS


Portfolio Homepage


*/